move_x = 0;
move_y = 0;
grv = 1;
spd = 10;
isGround = false;
HP = 100;
one_hp = HP / 6;
MP = 100;
one_mp = MP / 6;
aim_vector = point_direction(0, 0, 0, 0);
Exp = 0;
quests = ds_list_create();

unlocked_spells = ds_map_create();
ds_map_add(unlocked_spells, "abcd", obj_spell_ASDF);
ds_map_add(unlocked_spells, "aaaa", obj_spell_AAAA);
current_sphere = 0;
current_colour = 0;
colours[0] = 0;
colours[1] = 0;
colours[2] = 0;
colours[3] = 0;